# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  طلب سحب :
    الفروع : [  "الرئيسي"  ]

  # يسمح لك بتشغيل سير العمل هذا يدويًا من علامة التبويب "الإجراءات"
  workflow_dispatch :

# تتكون عملية تشغيل سير العمل من مهمة واحدة أو أكثر يمكن تشغيلها بالتتابع أو بالتوازي
الوظائف :
  # تتضمن عملية سير العمل هذه مهمة واحدة تسمى "بناء"
  يبني :
    # نوع جهاز التشغيل الذي سيتم تشغيل المهمة عليه
    يعمل على : أحدث إصدار من أوبونتو

    # تمثل الخطوات سلسلة من المهام التي سيتم تنفيذها كجزء من العمل
    ريس :
      # يقوم هذا الأمر باستخراج مستودعك الموجود ضمن $GITHUB_WORKSPACE، حتى تتمكن مهمتك من الوصول إليه.
      - يستخدم : actions/checkout@v4

      # يُشغّل أمرًا واحدًا باستخدام واجهة سطر الأوامر الخاصة بالمشغلين
      - الاسم : تشغيل نص برمجي من سطر واحد
        تشغيل : صدى مرحباً بالعالم!

      # يُشغّل مجموعة من الأوامر باستخدام واجهة سطر الأوامر الخاصة بالمشغلين
      - الاسم : تشغيل نص برمجي متعدد الأسطر
        تشغيل : |
          أضف إجراءات أخرى للبناء،
          قم بإجراء اختبار الصدى، ثم انشر مشروعك.
